[theme]
base = "light"
primaryColor = "#4F46E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#FBFBFD"
textColor = "#0B1020"
font = "sans serif"

[server]
maxUploadSize = 50

[browser]
gatherUsageStats = false
